### ISSUE TITLE
Not find file ticket.php and  HTTP 500 Error

### ISSUE THREAD

**Issue by TatoTognete** [JulioAugustoS/glpiorderservice#10]
Dear friend,

I downloaded the service order plugin, but I could not activate it because I did not find the ticket.php file in the INC folder, I tried to make changes to the ticket.class.php file and my GLPI gets HTTP 500 error, could help me please.

**Comment by JulioAugustoS** [comment]
Hello, my friend, in this current version of the plugin you really have to do change directly in the source code of glpi but I'm finishing the version 2.0 of the plugin where it will no longer be necessary to do this because an OS Print tab will be included directly in the ticket page, if you can wait until tomorrow, I'm going to go up to version 2.0, you already install it, it's going to be all right. If you need anything, I'm at your disposal.

**Comment by JulioAugustoS** [comment]
Friend, I uploaded the version 2.0.0 of the plugin, if you can download later and test thank you, anything is just to get in touch.

Thank you.
